
version: "3.7"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    image: trends:latest
    command: gunicorn -b 0.0.0.0:5000 api:app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    links:
      - redis


  worker:
    image: trends:latest
    command: rq worker --url redis://redis:6379 r_queue # Connects queue and Redis
    depends_on:
      - redis
    links:
      - redis


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - api
